server:
  port: 8080

spring:
  application:
    name: findteam
  datasource:
    url: jdbc:h2:mem:findteam
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:}
